# -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFr4oQ4mw9TBWmA-F04ZZgbiu0qziPbn
"""

import numpy as np

sample_size=1000000

x_data=np.random.uniform(0,1,sample_size)
y_data=np.random.uniform(0,1,sample_size)
count=0

for i in range(sample_size):
    if 0.25<x_data[i]<0.75:
        if 0.25<y_data[i]<0.75:
            if x_data[i]-y_data[i]>0.25 or  x_data[i]-y_data[i]<-0.25:
                count+=1 
print("Experimental probability and theoritical probability:{}---{}".format(count/sample_size,1/16))